name = "SplittablesTesting"
uuid = "3bda5eb5-c32a-4f64-8618-df3be8968470"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
SplittablesBase = "171d559e-b47b-412a-8079-5efa626c420e"

[compat]
SplittablesBase = "0.1.7"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
